theme: jekyll-theme-minimal
title: Katharina Burchin - Cloud & DevOps 
description: Head in the clouds, hands on the keyboard! This is where I share my Cloud/DevOps journey. Alongside hands-on cloud work, I actively broaden my understanding of the technical and historical foundations of modern computing and infrastructure, with a strong interest in how technology, systems, and society evolve together. 
